name: bochk-project
services:
  ocr-server:
    build: .
    image: bochk-ocr-server:0.0.1
    container_name: bochk-ocr-server
    ports:
      - "38080:8080"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - MOONSHOT_API_KEY=${MOONSHOT_API_KEY}
